### ISSUE TITLE
[Feature Request] Load a list of JavaScript files from a JSON file

### ISSUE THREAD

**Issue by KernelDeimos** [coderaiser/join-io#3]
In a lot of my past PHP projects, I had a script I wrote that would "include a folder". It did this by first loading a file called jspackage.json in that folder, which listed the paths - ordered, relative to the JSON file - of JavaScript files to be loaded. The the script would combine all this into one clump of JavaScript and send it to the client.

It would be really cool, I think, to bring that same functionality to Express, and this seems like the right module to do so. This is something I might have time to implement in the next couple of weeks.

**Comment by coderaiser** [comment]
What `GET` request it suppose to use to load bundle? It looks like a bit different approach. Do you want to add to middleware initialisation array of names and send all of them as stream for

```
GET /join/bundle.js
```

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
