### ISSUE TITLE
join-io doesn't work if prefix (other than "join") is passed in options

### ISSUE THREAD

**Issue by ivofrolov** [coderaiser/join-io#4]

**Comment by coderaiser** [comment]
Looks like the `prefix` [should be set earler](https://github.com/coderaiser/join-io/blob/v1.4.4/lib/join.js#L43).

Good idea for a pull request with fix :)

**Comment by coderaiser** [comment]
Fixed with https://github.com/coderaiser/join-io/pull/5.
